feat: define api scheme
DE-labtory/zulu pull request #15
Opened 2020-07-26 08:24 UTC by junbeomlee

2020-07-27 02:13 UTC, hea9549 commented
- 1월렛 1코인인가요??

- 월렛 생성시 패스워드 받는걸로 되어있는데, transfer 쪽 보면 패스워드를 받지는 않는 것 같아서 
만드는 월렛 api상에서는 앞쪽에서 인증을 받고 나서 사용만 가능하게끔 되는거면, wallet 생성시 password가 아니라 seed같은걸 받아야할듯함니당

2020-07-27 13:19 UTC, gurrpi commented
#### Continuing discussion from https://github.com/DE-labtory/zulu/pull/13#issuecomment-663957600

> I agree with the performance issue when looking up the balance. However, from the user's point of view, i think they would like to check the overall balance at once, and since we do not currently support many coins, the performance issue seems to be fine now, but it seems that there will be enough problems with balance later. what do you think?

@junbeomlee  Good point, I agree with you.

There is a alternative from removing `balance` field: add another API which provides wallet balance. This API would be provided to a user with a notice that a little delay might be accompanied when calling this API.

But this idea seems not good because it might add just a complexity that hassles us. 

So defer performance concern until when it really occurs seems to be a practical approach.

2020-07-28 12:51 UTC, zeroFruit commented
**nitpick**: Ugly markdown
There's '\\' character which makes markdown ugly. It would be better to remove '\\'.

**suggestion**: "id" field is not intuitive.
I think the "id" field on the `coins/` or `wallets/` endpoint makes the user feel coin as an entity. So I suggest "alias" instead of "id". Plus instead of hashing value, how about human-readable value like "ethereum_ropsten_ETH", "ethereum_ropsten_TKN" so that user can more easily identitify coin types.

**suggestion**: "meta" is not intuitive and definition of 'metadata' is 'data about data'
I think it would be better to name it as "platform_specifics" which shows the intention of that field more precisely.

**suggestion**: suggest 'Show Wallets' Success Response field name

AS-IS
```
{
    "id": "e372988fb3b2108",
    "scheme": "multiSig",
    "addresses": [
        {
```
SUGGESTION
```
{
    "id": "e372988fb3b2108",
    "scheme": "multiSig",
    "kinds": [
        {
```
Other than 'specs', 'types' would be good. I think "addresses" not imply the whole nested field.

**question**: Do we support multiple wallets on the same platform?
I ask this question because of the sample response of 'Show Wallets'.
```
{
    "id": "e372988fb3b2108",
    "scheme": "multiSig",
    "addresses": [
        {
            "address": "0x3a065000ab4183c6bf581dc1e55a605455fc6d61",
            "coin": {
                "id": "988f08b3b21e372",
                "blockchain": {
                    "platform": "ethereum",
                    "network": "ropsten"
                },
                "symbol": "eth",
                "decimals": 18,
                "meta": {}
            },
            "balance": "38089899992"
        },
        {
            "address": "0x3a065000ab4183c6bf581dc1e55a605455fc6d61",
            "coin": {
                "id": "988f08b3b21e372",
                "blockchain": {
                    "platform": "ethereum",
                    "network": "ropsten"
                },
                "symbol": "zulu",
                "decimals": 18,
                "meta": {}
            },
            "balance": "389992"
        },
```

2020-07-29 11:02 UTC, hihiboss commented on types/address.go
> +type Address struct {
I understand that this struct seems like data of wallet. But this struct name is `Address`.

Why use `Address` for struct name?

2020-07-29 11:02 UTC, hihiboss commented on docs/API.md
> + /coin/{id}
typo!
```suggestion
 /coins/{id}
```

2020-07-29 11:02 UTC, hihiboss commented on docs/API.md
> +curl --request GET 'localhost:8080/wallets
typo!
```suggestion
curl --request GET 'localhost:8080/wallets'
```

2020-07-29 11:02 UTC, hihiboss commented on docs/API.md
> +   `POST`
Markdown line break is needed!

```suggestion
   `POST`
   
```

2020-07-29 11:02 UTC, hihiboss commented on docs/API.md
> +curl --request GET 'localhost:8080/wallets --data '{ "scheme": "multiSig", "password": "password", "meta":{}}'
typo!

```suggestion
curl --request POST 'localhost:8080/wallets' --data '{ "scheme": "multiSig", "password": "password", "meta":{}}'
```

2020-07-29 11:02 UTC, hihiboss commented on docs/API.md
> +curl --request GET 'localhost:8080/wallets/3c6bf581dc1e55/transfer --data \
typo!

```suggestion
curl --request POST 'localhost:8080/wallets/3c6bf581dc1e55/transfer' --data \
```

2020-07-29 11:02 UTC, hihiboss commented on docs/API.md
> +    "hash": "0x3a065000ab4183c6bf581dc1e55a605455fc6d61",
`to`, `id` are also hash value. So, I think `hash` might be confusing. 

I suggest `tx` instead of `hash`.
```suggestion
    "tx": "0x3a065000ab4183c6bf581dc1e55a605455fc6d61",
```

2020-07-29 11:02 UTC, hihiboss commented on docs/API.md
> +Returns data about all wallets
At first, I thought it returns data about **all wallets**.
But, it seems like returning data about **a wallet** for all coin.

`Returns data about all wallets` confused me. 

So, I suggest `Show wallet` or `Show wallet data` to title.
And, `Returns data about wallet` to explanation.

2020-07-29 11:06 UTC, hihiboss commented on types/address.go
> +type Address struct {
@zeroFruit also said about this.
> Other than 'kinds', 'specs', 'types' would be good. I think "addresses" not imply the nested field well.

2020-07-30 14:03 UTC, zeroFruit commented
**suggestion**: How about rename "types" package into "http"?

- These structs are all related to the web interface of service.  
- I think instead of `types.ListCoinsRequest`, `http.ListCoinsRequest` naming is more explicit.

**suggestion**: How about put all HTTP related thing such as HTTP request/response scheme to `types.go` or `scheme.go` instead of place all single request/response into separate file (for example, `wallet_create_request.go`, `wallet_create_response.go`).

2020-07-31 03:52 UTC, hihiboss commented
@zeroFruit 

> suggestion: How about rename "types" package into "http"?
>
> - These structs are all related to the web interface of service.
> - I think instead of types.ListCoinsRequest, http.ListCoinsRequest naming is more explicit.

But, types like `address`, `balance`, `blockchain` which are not request/response are not only related to `http`.
`http.address`, `http.balance`, `http.blockchain` would be confusing. 

So, I suggest that some types like request/response are placed in `http` and the other are placed in `types`.

2020-07-31 07:11 UTC, junbeomlee commented
모두 반영해서 올렸습니다!

2020-07-31 07:21 UTC, hihiboss requested changes

2020-07-31 07:21 UTC, hihiboss commented on docs/API.md
> +curl --request POST 'localhost:8080/wallets' --data '{ "scheme": "multiSig", "password": "password", "meta":{}}
typo!

```suggestion
curl --request POST 'localhost:8080/wallets' --data '{ "scheme": "multiSig", "password": "password", "meta":{}}'
```

2020-07-31 07:26 UTC, hihiboss requested changes

2020-07-31 07:26 UTC, hihiboss commented on docs/API.md
> +curl --request GET 'localhost:8080/wallets'
`id` is needed!

```suggestion
curl --request GET 'localhost:8080/wallets/{id}'
```

2020-07-31 07:26 UTC, hihiboss commented on docs/API.md
> +curl --request POST 'localhost:8080/wallets' --data '{ "scheme": "multiSig", "password": "password", "meta":{}}
Please check this again!

2020-08-01 05:35 UTC, hihiboss approved these changes
LGTM 👍

2020-08-01 05:35 UTC, merged