WIP: Keychain
DE-labtory/zulu pull request #33
Opened 2020-08-16 05:04 UTC by gurrpi

## TODO

*  key store using levelDB
* tests for keychain/mem/store.go

2020-08-18 02:32 UTC, hea9549 requested changes

2020-08-18 02:32 UTC, hea9549 commented on keychain/mem/store.go
>  type MemStore struct {
`mem` 이 패키지네임이니까 `mem.KeyStore`, `mem.NewKeyStore`같은 형식을 취하게 되야할것같습니다~
`MemStore` -> `KeyStore`로 변경 어떤가요?

2020-08-19 15:50 UTC, gurrpi commented on keychain/mem/store.go
>  type MemStore struct {
반영 완료!

2020-08-22 07:04 UTC, junbeomlee approved these changes

2020-08-22 07:05 UTC, merged